# This lab is to deal with **SVM** to classification tasks and compare its performance with other competitive algorithms. In general, **SVM** is one of the most popular and widely used supervised machine learning algorithms.

*   **Deadline: 23:59, 17/03/2023**



# Import libraries

In [9]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/ML


In [10]:
# code
from sklearn.datasets import load_breast_cancer
from sklearn import svm
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.svm import SVC
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn import datasets

#Task 1. 
For breast cancer dataset (https://tinyurl.com/3vme8hr3) which could be loaded from datasets in sklearn as follows:

```
#Import scikit-learn dataset library
from sklearn import datasets

#Load dataset
cancer = datasets.load_breast_cancer()
```

*   1.1.	Apply SVM algorithm to above dataset using linear kernel.
*   1.2.	Compare the obtained results with other competitive algorithms (Logistic Regression, Decision Tree, kNN) based on metrics: accuracy, precision, recall, f1 measures.



In [27]:
# code
from sklearn import datasets
cancer = datasets.load_breast_cancer()


In [28]:
print("Features: ", cancer.feature_names)
print("Labels: ", cancer.target_names)

Features:  ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Labels:  ['malignant' 'benign']


In [29]:
cancer.data.shape

(569, 30)

In [30]:
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [31]:
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3,random_state=109)

In [32]:
clf = svm.SVC(kernel='linear')


In [33]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [34]:
y_pred = clf.predict(X_test)

In [35]:
confusion = confusion_matrix(y_test, y_pred)

In [36]:
print(confusion_matrix(y_test, y_pred))

[[ 61   2]
 [  4 104]]


In [37]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre = round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [38]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  0.9649122807017544
Precision :  0.9649122807017544
Recall :  0.9649122807017544
F1 :  0.9649122807017544


In [3]:
# 1.2
from sklearn import datasets
cancer = datasets.load_breast_cancer()
cancer = datasets.load_iris()

In [4]:
# LogisticRegression
X= cancer.data
y = cancer.target
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3,random_state=109)
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier.fit(X_train, y_train) 
y_pred1 = classifier.predict(X_test)

In [5]:
confusion = confusion_matrix(y_test, y_pred1)

In [6]:
print(confusion_matrix(y_test, y_pred1))

[[12  0  0]
 [ 0 15  2]
 [ 0  1 15]]


In [7]:
acc1 = round(accuracy_score(y_test, y_pred1), 2)
pre1 = round(precision_score(y_test, y_pred1, average='micro'), 2)
recall1 = round(recall_score(y_test, y_pred1, average='micro'), 2)
f11 = round(f1_score(y_test, y_pred1, average='micro'), 2)

In [8]:
print ("Accuracy : ", accuracy_score(y_test, y_pred1))
print ("Precision : ", precision_score(y_test, y_pred1,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred1, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred1, average='micro'))

Accuracy :  0.9333333333333333
Precision :  0.9333333333333333
Recall :  0.9333333333333333
F1 :  0.9333333333333333


In [9]:
# Decision Tree
clf1 = tree.DecisionTreeClassifier()

In [14]:
clf1.fit(X_train, y_train)

DecisionTreeClassifier()

In [11]:
y_pred2 = clf1.predict(X_test)

In [12]:
confusion = confusion_matrix(y_test, y_pred2)

In [13]:
print(confusion_matrix(y_test, y_pred2))

[[12  0  0]
 [ 0 15  2]
 [ 0  3 13]]


In [15]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2 = round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12 = round(f1_score(y_test, y_pred2, average='micro'), 2)

In [16]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  0.8888888888888888
Precision :  0.8888888888888888
Recall :  0.8888888888888888
F1 :  0.8888888888888888


In [17]:
#KNN
model = KNeighborsClassifier(n_neighbors=3)

In [18]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [19]:
y_pred3 = model.predict(X_test)

In [20]:
confusion = confusion_matrix(y_test, y_pred3)

In [21]:
print(confusion_matrix(y_test, y_pred3))

[[12  0  0]
 [ 0 14  3]
 [ 0  1 15]]


In [24]:
acc3 = round(accuracy_score(y_test, y_pred3), 2)
pre3= round(precision_score(y_test, y_pred3, average='micro'), 2)
recall3 = round(recall_score(y_test, y_pred3, average='micro'), 2)
f13 = round(f1_score(y_test, y_pred3, average='micro'), 2)

In [25]:
print ("Accuracy : ", accuracy_score(y_test, y_pred3))
print ("Precision : ", precision_score(y_test, y_pred3,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred3, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred3, average='micro'))

Accuracy :  0.9111111111111111
Precision :  0.9111111111111111
Recall :  0.9111111111111111
F1 :  0.9111111111111111


In [39]:
from prettytable import PrettyTable

t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])

t.add_row(['SVM',acc,pre,recall,f1])
t.add_row(['LogisticRegression',acc1,pre1,recall1,f11])
t.add_row(['Decision Tree',acc2,pre2,recall2,f12])
t.add_row(['kNN',acc3,pre3,recall3,f13])
print(t)

+--------------------+----------+-----------+--------+------+
|      Compare       | Accuracy | Precision | Recall |  F1  |
+--------------------+----------+-----------+--------+------+
|        SVM         |   0.96   |    0.96   |  0.96  | 0.96 |
| LogisticRegression |   0.93   |    0.93   |  0.93  | 0.93 |
|   Decision Tree    |   0.91   |    0.91   |  0.91  | 0.91 |
|        kNN         |   0.91   |    0.91   |  0.91  | 0.91 |
+--------------------+----------+-----------+--------+------+


#Task 2. 

*   1.1.	Perform SVM algorithm to **Iris dataset** using **linear kernel**.
*   1.2.	Compare the obtained results in 1.1 with SVM using other kernels (**Polynomial Kernel, Gaussian Kernel, Sigmoid Kernel, Radial Basis Function Kernel**). Some metrics could be used: accuracy, precision, recall, f1 measures





In [193]:
# code
# 1.1
from sklearn import datasets
iris = datasets.load_iris()

In [194]:
X_train = iris.data[:, :]
y_train = iris.target

In [195]:
X_train, X_test, y_train, y_test = train_test_split(
                        iris.data[:, :], iris.target, test_size=0.2, random_state=42)

In [196]:
clf = svm.SVC(kernel='linear')

In [197]:
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [198]:
y_pred = clf.predict(X_test)

In [199]:
confusion = confusion_matrix(y_test, y_pred)

In [200]:
print(confusion_matrix(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [201]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre= round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [202]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [203]:
# 1.2
# Polynomial Kernel
poly_svm = svm.SVC(kernel='poly', degree=3)

In [204]:
poly_svm.fit(X_train, y_train)

SVC(kernel='poly')

In [205]:
y_pred2 = poly_svm.predict(X_test)

In [206]:
confusion = confusion_matrix(y_test, y_pred2)

In [207]:
print(confusion_matrix(y_test, y_pred2))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [208]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2= round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12 = round(f1_score(y_test, y_pred2, average='micro'), 2)

In [209]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [210]:
#Gaussian Kernel
rbf_svm = svm.SVC(kernel='rbf')

In [211]:
rbf_svm.fit(X_train, y_train)

SVC()

In [212]:
y_pred3 = rbf_svm.predict(X_test)

In [213]:
confusion = confusion_matrix(y_test, y_pred3)

In [214]:
print(confusion_matrix(y_test, y_pred3))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [215]:
acc3 = round(accuracy_score(y_test, y_pred3), 2)
pre3= round(precision_score(y_test, y_pred3, average='micro'), 2)
recall3 = round(recall_score(y_test, y_pred3, average='micro'), 2)
f13 = round(f1_score(y_test, y_pred3, average='micro'), 2)

In [216]:
print ("Accuracy : ", accuracy_score(y_test, y_pred3))
print ("Precision : ", precision_score(y_test, y_pred3,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred3, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred3, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [217]:
#Sigmoid Kernel
sigmoid_svm = svm.SVC(kernel='sigmoid')

In [218]:
sigmoid_svm.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [219]:
y_pred4 = sigmoid_svm.predict(X_test)

In [220]:
confusion = confusion_matrix(y_test, y_pred4)

In [221]:
print(confusion_matrix(y_test, y_pred4))

[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]


In [222]:
acc4 = round(accuracy_score(y_test, y_pred4), 2)
pre4= round(precision_score(y_test, y_pred4, average='micro'), 2)
recall4 = round(recall_score(y_test, y_pred4, average='micro'), 2)
f14 = round(f1_score(y_test, y_pred4, average='micro'), 2)

In [223]:
print ("Accuracy : ", accuracy_score(y_test, y_pred4))
print ("Precision : ", precision_score(y_test, y_pred4,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred4, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred4, average='micro'))

Accuracy :  0.3
Precision :  0.3
Recall :  0.3
F1 :  0.3


In [224]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['Linear Kernel',acc,pre,recall,f1])
t.add_row(['Polynomial Kernel',acc2,pre2,recall2,f12])
t.add_row(['Gaussian Kernel(rbf)',acc3,pre3,recall3,f13])
t.add_row(['Sigmoid Kernel',acc4,pre4,recall4,f14])
print(t)

+----------------------+----------+-----------+--------+-----+
|       Compare        | Accuracy | Precision | Recall |  F1 |
+----------------------+----------+-----------+--------+-----+
|    Linear Kernel     |   1.0    |    1.0    |  1.0   | 1.0 |
|  Polynomial Kernel   |   1.0    |    1.0    |  1.0   | 1.0 |
| Gaussian Kernel(rbf) |   1.0    |    1.0    |  1.0   | 1.0 |
|    Sigmoid Kernel    |   0.3    |    0.3    |  0.3   | 0.3 |
+----------------------+----------+-----------+--------+-----+


#Task 3. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with mnist dataset based on accuracy, precision, recall, f1 measures.


In [233]:
mnist = datasets.load_digits()

In [234]:
X = mnist['data']
y = mnist['target']

In [235]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [236]:
# DecisionTree
dtc = DecisionTreeClassifier()

In [237]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [238]:
y_pred = dtc.predict(X_test)

In [239]:
confusion = confusion_matrix(y_test, y_pred)

In [240]:
print(confusion_matrix(y_test, y_pred))

[[29  0  1  0  1  1  0  1  0  0]
 [ 0 21  1  1  3  0  0  0  1  1]
 [ 1  0 24  3  0  0  1  1  3  0]
 [ 0  0  1 30  0  0  0  0  1  2]
 [ 0  0  0  1 42  1  1  1  0  0]
 [ 0  0  3  0  2 41  0  0  0  1]
 [ 0  0  1  0  1  0 33  0  0  0]
 [ 0  0  1  1  1  0  0 31  0  0]
 [ 0  3  0  1  0  1  0  0 22  3]
 [ 0  1  0  4  1  0  0  4  0 30]]


In [241]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre= round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [242]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  0.8416666666666667
Precision :  0.8416666666666667
Recall :  0.8416666666666667
F1 :  0.8416666666666667


In [243]:
# KNeighborsClassifier
knn = KNeighborsClassifier()

In [244]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [245]:
y_pred2 = knn.predict(X_test)

In [246]:
confusion = confusion_matrix(y_test, y_pred2)

In [247]:
print(confusion_matrix(y_test, y_pred2))

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 45  1  0  0  1]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  0  0  0 30  0]
 [ 0  0  0  0  1  1  0  0  0 38]]


In [248]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2= round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12 = round(f1_score(y_test, y_pred2, average='micro'), 2)

In [249]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  0.9861111111111112
Precision :  0.9861111111111112
Recall :  0.9861111111111112
F1 :  0.9861111111111112


In [250]:
# LogisticRegression
lr = LogisticRegression()

In [251]:
lr.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [252]:
y_pred3 = lr.predict(X_test)

In [253]:
confusion = confusion_matrix(y_test, y_pred3)

In [254]:
print(confusion_matrix(y_test, y_pred3))

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  1  0  0 44  0  1  0  0  0]
 [ 0  0  1  0  0 44  1  0  0  1]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  1  0 33  0  0]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  0  0  0  0  1 38]]


In [255]:
acc3 = round(accuracy_score(y_test, y_pred3), 2)
pre3= round(precision_score(y_test, y_pred3, average='micro'), 2)
recall3 = round(recall_score(y_test, y_pred3, average='micro'), 2)
f13 = round(f1_score(y_test, y_pred3, average='micro'), 2)

In [256]:
print ("Accuracy : ", accuracy_score(y_test, y_pred3))
print ("Precision : ", precision_score(y_test, y_pred3,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred3, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred3, average='micro'))

Accuracy :  0.9694444444444444
Precision :  0.9694444444444444
Recall :  0.9694444444444444
F1 :  0.9694444444444444


In [257]:
# linear
svc_linear = SVC(kernel='linear')

In [258]:
svc_linear.fit(X_train, y_train)

SVC(kernel='linear')

In [259]:
y_pred4 = svc_linear.predict(X_test)

In [260]:
confusion = confusion_matrix(y_test, y_pred4)

In [261]:
print(confusion_matrix(y_test, y_pred4))

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  1]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  1  0  0  1  0 37]]


In [262]:
acc4 = round(accuracy_score(y_test, y_pred4), 2)
pre4= round(precision_score(y_test, y_pred4, average='micro'), 2)
recall4 = round(recall_score(y_test, y_pred4, average='micro'), 2)
f14 = round(f1_score(y_test, y_pred4, average='micro'), 2)

In [263]:
print ("Accuracy : ", accuracy_score(y_test, y_pred4))
print ("Precision : ", precision_score(y_test, y_pred4,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred4, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred4, average='micro'))

Accuracy :  0.9777777777777777
Precision :  0.9777777777777777
Recall :  0.9777777777777777
F1 :  0.9777777777777777


In [264]:
# poly
svc_poly = SVC(kernel='poly')

In [265]:
svc_poly.fit(X_train, y_train)

SVC(kernel='poly')

In [266]:
y_pred5 = svc_poly.predict(X_test)

In [267]:
confusion = confusion_matrix(y_test, y_pred5)

In [268]:
print(confusion_matrix(y_test, y_pred5))

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  0  0  0 30  0]
 [ 0  0  0  0  0  0  0  1  0 39]]


In [269]:
acc5 = round(accuracy_score(y_test, y_pred5), 2)
pre5= round(precision_score(y_test, y_pred5, average='micro'), 2)
recall5 = round(recall_score(y_test, y_pred5, average='micro'), 2)
f15 = round(f1_score(y_test, y_pred5, average='micro'), 2)

In [270]:
print ("Accuracy : ", accuracy_score(y_test, y_pred5))
print ("Precision : ", precision_score(y_test, y_pred5,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred5, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred5, average='micro'))

Accuracy :  0.9916666666666667
Precision :  0.9916666666666667
Recall :  0.9916666666666667
F1 :  0.9916666666666667


In [271]:
# gaussian (rbf)
svc_rbf = SVC(kernel='rbf')

In [272]:
svc_rbf.fit(X_train, y_train)

SVC()

In [273]:
y_pred6 = svc_rbf.predict(X_test)

In [274]:
confusion = confusion_matrix(y_test, y_pred6)

In [275]:
print(confusion_matrix(y_test, y_pred6))

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  0  0  0 29  1]
 [ 0  0  0  0  0  1  0  1  0 38]]


In [276]:
acc6 = round(accuracy_score(y_test, y_pred6), 2)
pre6= round(precision_score(y_test, y_pred6, average='micro'), 2)
recall6 = round(recall_score(y_test, y_pred6, average='micro'), 2)
f16 = round(f1_score(y_test, y_pred6, average='micro'), 2)

In [277]:
print ("Accuracy : ", accuracy_score(y_test, y_pred6))
print ("Precision : ", precision_score(y_test, y_pred6,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred6, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred6, average='micro'))

Accuracy :  0.9861111111111112
Precision :  0.9861111111111112
Recall :  0.9861111111111112
F1 :  0.9861111111111112


In [281]:
# sigmoid
svc_sigmoid = SVC(kernel='sigmoid')

In [282]:
svc_sigmoid.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [283]:
y_pred7 = svc_sigmoid.predict(X_test)

In [284]:
confusion = confusion_matrix(y_test, y_pred7)

In [285]:
print(confusion_matrix(y_test, y_pred7))

[[31  0  0  0  2  0  0  0  0  0]
 [ 0 21  0  0  2  0  0  1  2  2]
 [ 0  2 29  0  0  0  1  0  1  0]
 [ 0  1  0 32  0  0  0  0  1  0]
 [ 1  1  0  0 44  0  0  0  0  0]
 [ 0  0  0  0  0 44  1  0  0  2]
 [ 1  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  4  1  0  0  1  0  0 22  2]
 [ 0  2  0  0  0  1  0  1  2 34]]


In [287]:
acc7 = round(accuracy_score(y_test, y_pred7), 2)
pre7= round(precision_score(y_test, y_pred7, average='micro'), 2)
recall7 = round(recall_score(y_test, y_pred7, average='micro'), 2)
f17 = round(f1_score(y_test, y_pred7, average='micro'), 2)

In [288]:
print ("Accuracy : ", accuracy_score(y_test, y_pred7))
print ("Precision : ", precision_score(y_test, y_pred7,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred7, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred7, average='micro'))

Accuracy :  0.9
Precision :  0.9
Recall :  0.9
F1 :  0.9


In [289]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Linear Kernel',acc4,pre4,recall4,f14])
print(t)

+--------------------+----------+-----------+--------+------+
|      Compare       | Accuracy | Precision | Recall |  F1  |
+--------------------+----------+-----------+--------+------+
|    DecisionTree    |   0.84   |    0.84   |  0.84  | 0.84 |
|        kNN         |   0.99   |    0.99   |  0.99  | 0.99 |
| LogisticRegression |   0.97   |    0.97   |  0.97  | 0.97 |
|   Linear Kernel    |   0.98   |    0.98   |  0.98  | 0.98 |
+--------------------+----------+-----------+--------+------+


In [290]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Polynomial Kernel',acc5,pre5,recall5,f15])
print(t)

+--------------------+----------+-----------+--------+------+
|      Compare       | Accuracy | Precision | Recall |  F1  |
+--------------------+----------+-----------+--------+------+
|    DecisionTree    |   0.84   |    0.84   |  0.84  | 0.84 |
|        kNN         |   0.99   |    0.99   |  0.99  | 0.99 |
| LogisticRegression |   0.97   |    0.97   |  0.97  | 0.97 |
| Polynomial Kernel  |   0.99   |    0.99   |  0.99  | 0.99 |
+--------------------+----------+-----------+--------+------+


In [292]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Gaussian Kernel(rbf)',acc6,pre6,recall6,f16])
print(t)

+----------------------+----------+-----------+--------+------+
|       Compare        | Accuracy | Precision | Recall |  F1  |
+----------------------+----------+-----------+--------+------+
|     DecisionTree     |   0.84   |    0.84   |  0.84  | 0.84 |
|         kNN          |   0.99   |    0.99   |  0.99  | 0.99 |
|  LogisticRegression  |   0.97   |    0.97   |  0.97  | 0.97 |
| Gaussian Kernel(rbf) |   0.99   |    0.99   |  0.99  | 0.99 |
+----------------------+----------+-----------+--------+------+


In [293]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Sigmoid Kernel',acc7,pre7,recall7,f17])
print(t)

+--------------------+----------+-----------+--------+------+
|      Compare       | Accuracy | Precision | Recall |  F1  |
+--------------------+----------+-----------+--------+------+
|    DecisionTree    |   0.84   |    0.84   |  0.84  | 0.84 |
|        kNN         |   0.99   |    0.99   |  0.99  | 0.99 |
| LogisticRegression |   0.97   |    0.97   |  0.97  | 0.97 |
|   Sigmoid Kernel   |   0.9    |    0.9    |  0.9   | 0.9  |
+--------------------+----------+-----------+--------+------+


#Task 4. 
Compare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression) and SVM (using different kernels) with **credit card dataset** based on accuracy, precision, recall, f1 measures.

*   Give some comments on the obtained results
*   Identify issues with dataset, and propose the solutions to these issues



In [11]:
# code
data = pd.read_csv('Lab5/creditcard.csv')
data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [12]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# DecisionTree
dtc = DecisionTreeClassifier()

In [19]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [20]:
y_pred = dtc.predict(X_test)

In [21]:
confusion = confusion_matrix(y_test, y_pred)

In [22]:
print(confusion_matrix(y_test, y_pred))

[[56833    31]
 [   18    80]]


In [23]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre= round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [24]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  0.9991397773954567
Precision :  0.9991397773954567
Recall :  0.9991397773954567
F1 :  0.9991397773954567


In [25]:
# KNeighborsClassifier
knn = KNeighborsClassifier()

In [26]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [27]:
y_pred2 = knn.predict(X_test)

In [28]:
confusion = confusion_matrix(y_test, y_pred2)

In [43]:
print(confusion_matrix(y_test, y_pred2))

[[56864     0]
 [   93     5]]


In [38]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2= round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12 = round(f1_score(y_test, y_pred2, average='micro'), 2)

In [40]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  0.9983673326077034
Precision :  0.9983673326077034
Recall :  0.9983673326077034
F1 :  0.9983673326077034


In [31]:
# LogisticRegression
lr = LogisticRegression()

In [32]:
lr.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [33]:
y_pred3 = lr.predict(X_test)

In [34]:
confusion = confusion_matrix(y_test, y_pred3)

In [35]:
print(confusion_matrix(y_test, y_pred3))

[[56836    28]
 [   30    68]]


In [41]:
acc3 = round(accuracy_score(y_test, y_pred3), 2)
pre3= round(precision_score(y_test, y_pred3, average='micro'), 2)
recall3 = round(recall_score(y_test, y_pred3, average='micro'), 2)
f13= round(f1_score(y_test, y_pred3, average='micro'), 2)

In [42]:
print ("Accuracy : ", accuracy_score(y_test, y_pred3))
print ("Precision : ", precision_score(y_test, y_pred3,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred3, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred3, average='micro'))

Accuracy :  0.9989817773252344
Precision :  0.9989817773252344
Recall :  0.9989817773252344
F1 :  0.9989817773252344


In [44]:
# linear
svc_linear = SVC(kernel='linear')

In [45]:
svc_linear.fit(X_train, y_train)

SVC(kernel='linear')

In [46]:
y_pred4 = svc_linear.predict(X_test)

In [47]:
confusion = confusion_matrix(y_test, y_pred4)

In [48]:
print(confusion_matrix(y_test, y_pred4))

[[56845    19]
 [   69    29]]


In [49]:
acc4 = round(accuracy_score(y_test, y_pred4), 2)
pre4= round(precision_score(y_test, y_pred4, average='micro'), 2)
recall4 = round(recall_score(y_test, y_pred4, average='micro'), 2)
f14= round(f1_score(y_test, y_pred4, average='micro'), 2)

In [50]:
print ("Accuracy : ", accuracy_score(y_test, y_pred4))
print ("Precision : ", precision_score(y_test, y_pred4,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred4, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred4, average='micro'))

Accuracy :  0.9984551104244935
Precision :  0.9984551104244935
Recall :  0.9984551104244935
F1 :  0.9984551104244935


In [51]:
# poly
svc_poly = SVC(kernel='poly')

In [52]:
svc_poly.fit(X_train, y_train)

SVC(kernel='poly')

In [53]:
y_pred5 = svc_poly.predict(X_test)

In [54]:
confusion = confusion_matrix(y_test, y_pred5)

In [55]:
print(confusion_matrix(y_test, y_pred5))

[[56864     0]
 [   98     0]]


In [56]:
acc5 = round(accuracy_score(y_test, y_pred5), 2)
pre5= round(precision_score(y_test, y_pred5, average='micro'), 2)
recall5 = round(recall_score(y_test, y_pred5, average='micro'), 2)
f15= round(f1_score(y_test, y_pred5, average='micro'), 2)

In [57]:
print ("Accuracy : ", accuracy_score(y_test, y_pred5))
print ("Precision : ", precision_score(y_test, y_pred5,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred5, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred5, average='micro'))

Accuracy :  0.9982795547909132
Precision :  0.9982795547909132
Recall :  0.9982795547909132
F1 :  0.9982795547909132


In [58]:
# gaussian(rbf)
svc_rbf = SVC(kernel='rbf')

In [59]:
svc_rbf.fit(X_train, y_train)

SVC()

In [60]:
y_pred6 = svc_rbf.predict(X_test)

In [61]:
confusion = confusion_matrix(y_test, y_pred6)

In [62]:
print(confusion_matrix(y_test, y_pred6))

[[56864     0]
 [   98     0]]


In [63]:
acc6 = round(accuracy_score(y_test, y_pred6), 2)
pre6= round(precision_score(y_test, y_pred6, average='micro'), 2)
recall6 = round(recall_score(y_test, y_pred6, average='micro'), 2)
f16= round(f1_score(y_test, y_pred6, average='micro'), 2)

In [64]:
print ("Accuracy : ", accuracy_score(y_test, y_pred6))
print ("Precision : ", precision_score(y_test, y_pred6,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred6, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred6, average='micro'))

Accuracy :  0.9982795547909132
Precision :  0.9982795547909132
Recall :  0.9982795547909132
F1 :  0.9982795547909132


In [65]:
# sigmoid
svc_sigmoid = SVC(kernel='sigmoid')

In [66]:
svc_sigmoid.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [67]:
y_pred7 = svc_sigmoid.predict(X_test)

In [68]:
confusion = confusion_matrix(y_test, y_pred7)

In [69]:
print(confusion_matrix(y_test, y_pred7))

[[56864     0]
 [   98     0]]


In [70]:
acc7 = round(accuracy_score(y_test, y_pred7), 2)
pre7= round(precision_score(y_test, y_pred7, average='micro'), 2)
recall7 = round(recall_score(y_test, y_pred7, average='micro'), 2)
f17= round(f1_score(y_test, y_pred7, average='micro'), 2)

In [71]:
print ("Accuracy : ", accuracy_score(y_test, y_pred7))
print ("Precision : ", precision_score(y_test, y_pred7,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred7, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred7, average='micro'))

Accuracy :  0.9982795547909132
Precision :  0.9982795547909132
Recall :  0.9982795547909132
F1 :  0.9982795547909132


In [72]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Linear Kernel',acc4,pre4,recall4,f14])
print(t)

+--------------------+----------+-----------+--------+-----+
|      Compare       | Accuracy | Precision | Recall |  F1 |
+--------------------+----------+-----------+--------+-----+
|    DecisionTree    |   1.0    |    1.0    |  1.0   | 1.0 |
|        kNN         |   1.0    |    1.0    |  1.0   | 1.0 |
| LogisticRegression |   1.0    |    1.0    |  1.0   | 1.0 |
|   Linear Kernel    |   1.0    |    1.0    |  1.0   | 1.0 |
+--------------------+----------+-----------+--------+-----+


In [73]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Polynomial Kernel',acc5,pre5,recall5,f15])
print(t)

+--------------------+----------+-----------+--------+-----+
|      Compare       | Accuracy | Precision | Recall |  F1 |
+--------------------+----------+-----------+--------+-----+
|    DecisionTree    |   1.0    |    1.0    |  1.0   | 1.0 |
|        kNN         |   1.0    |    1.0    |  1.0   | 1.0 |
| LogisticRegression |   1.0    |    1.0    |  1.0   | 1.0 |
| Polynomial Kernel  |   1.0    |    1.0    |  1.0   | 1.0 |
+--------------------+----------+-----------+--------+-----+


In [74]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Gaussian Kernel(rbf)',acc6,pre6,recall6,f16])
print(t)

+----------------------+----------+-----------+--------+-----+
|       Compare        | Accuracy | Precision | Recall |  F1 |
+----------------------+----------+-----------+--------+-----+
|     DecisionTree     |   1.0    |    1.0    |  1.0   | 1.0 |
|         kNN          |   1.0    |    1.0    |  1.0   | 1.0 |
|  LogisticRegression  |   1.0    |    1.0    |  1.0   | 1.0 |
| Gaussian Kernel(rbf) |   1.0    |    1.0    |  1.0   | 1.0 |
+----------------------+----------+-----------+--------+-----+


In [75]:
from prettytable import PrettyTable
t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])
t.add_row(['DecisionTree',acc,pre,recall,f1])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['LogisticRegression',acc3,pre3,recall3,f13])
t.add_row(['Sigmoid Kernel',acc7,pre7,recall7,f17])
print(t)

+--------------------+----------+-----------+--------+-----+
|      Compare       | Accuracy | Precision | Recall |  F1 |
+--------------------+----------+-----------+--------+-----+
|    DecisionTree    |   1.0    |    1.0    |  1.0   | 1.0 |
|        kNN         |   1.0    |    1.0    |  1.0   | 1.0 |
| LogisticRegression |   1.0    |    1.0    |  1.0   | 1.0 |
|   Sigmoid Kernel   |   1.0    |    1.0    |  1.0   | 1.0 |
+--------------------+----------+-----------+--------+-----+


#Finally,
Save a copy in your Github. Remember renaming the notebook.