# This lab is to deal with classification task using **Random Forests** and **Naïve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**



In [4]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/ML'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/ML


# Import libraries

In [31]:
# code
import numpy
import numpy as np
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.svm import SVC
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import CategoricalNB
import seaborn as sns

#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.



In [ ]:
# code
mnist = datasets.load_digits()

In [ ]:
X = mnist['data']
y = mnist['target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Random
clf=RandomForestClassifier(n_estimators=100)

In [ ]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred)

In [ ]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_pred))

Confusion matrix :
 [[32  0  0  0  1  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  1  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  2  0  0  0  1  0  0 27  0]
 [ 0  0  0  0  0  1  0  1  0 38]]


In [ ]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre = round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  0.9694444444444444
Precision :  0.9694444444444444
Recall :  0.9694444444444444
F1 :  0.9694444444444444


In [ ]:
# NaiveBayes using GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train, y_train) 

GaussianNB()

In [ ]:
y_pred1 = model.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred1)

In [ ]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_pred1))

Confusion matrix :
 [[31  0  0  0  0  1  0  1  0  0]
 [ 0 24  0  0  0  0  0  0  3  1]
 [ 0  2 20  0  0  0  1  0 10  0]
 [ 0  0  1 29  0  1  0  0  3  0]
 [ 0  0  0  0 38  0  1  7  0  0]
 [ 0  0  0  1  0 44  1  1  0  0]
 [ 0  0  0  0  1  0 34  0  0  0]
 [ 0  0  0  0  0  1  0 33  0  0]
 [ 0  2  0  0  0  0  0  2 26  0]
 [ 0  1  1  2  0  2  0  4  4 26]]


In [ ]:
acc1 = round(accuracy_score(y_test, y_pred1), 2)
pre1 = round(precision_score(y_test, y_pred1, average='micro'), 2)
recall1 = round(recall_score(y_test, y_pred1, average='micro'), 2)
f11 = round(f1_score(y_test, y_pred1, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred1))
print ("Precision : ", precision_score(y_test, y_pred1,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred1, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred1, average='micro'))

Accuracy :  0.8472222222222222
Precision :  0.8472222222222222
Recall :  0.8472222222222222
F1 :  0.8472222222222222


In [ ]:
# SVM 
clf1 = svm.SVC(kernel='linear')

In [ ]:
clf1.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred2 = clf1.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred2)

In [ ]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_pred2))

Confusion matrix :
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  1]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  1  0  0  1  0 37]]


In [ ]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2 = round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12 = round(f1_score(y_test, y_pred2, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  0.9777777777777777
Precision :  0.9777777777777777
Recall :  0.9777777777777777
F1 :  0.9777777777777777


In [ ]:
from prettytable import PrettyTable

t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])

t.add_row(['Random forest',acc,pre,recall,f1])
t.add_row(['NaiveBayes',acc1,pre1,recall1,f11])
t.add_row(['SVM',acc2,pre2,recall2,f12])
print(t)

+---------------+----------+-----------+--------+------+
|    Compare    | Accuracy | Precision | Recall |  F1  |
+---------------+----------+-----------+--------+------+
| Random forest |   0.97   |    0.97   |  0.97  | 0.97 |
|   NaiveBayes  |   0.85   |    0.85   |  0.85  | 0.85 |
|      SVM      |   0.98   |    0.98   |  0.98  | 0.98 |
+---------------+----------+-----------+--------+------+


#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')



In [ ]:
data = pd.read_csv('Lab/Lab6/bank.csv')
data

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [ ]:
#code
data = pd.read_csv('Lab/Lab6/bank.csv')

In [ ]:
scale = StandardScaler()
dt = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
dataset = data[dt]
data[['age', 'balance', 'day', 'campaign', 'pdays', 'previous']]= scale.fit_transform(dataset[['age', 'balance', 'day', 'campaign', 'pdays', 'previous']])
data

age          job  marital  education default   balance housing  \
0      1.491505       admin.  married  secondary      no  0.252525     yes   
1      1.239676       admin.  married  secondary      no -0.459974      no   
2     -0.019470   technician  married  secondary      no -0.080160     yes   
3      1.155733     services  married  secondary      no  0.293762     yes   
4      1.071790       admin.  married   tertiary      no -0.416876      no   
...         ...          ...      ...        ...     ...       ...     ...   
11157 -0.691015  blue-collar   single    primary      no -0.473616     yes   
11158 -0.187357     services  married  secondary      no -0.246658      no   
11159 -0.774958   technician   single  secondary      no -0.464934      no   
11160  0.148416   technician  married  secondary      no -0.473926      no   
11161 -0.607072   technician  married  secondary      no -0.473926      no   

      loan   contact       day month  duration  campaign     pdays  previous  \
0       no   unknown -1.265746   may      1042 -0.554168 -0.481184 -0.363260   
1       no   unknown -1.265746   may      1467 -0.554168 -0.481184 -0.363260   
2       no   unknown -1.265746   may      1389 -0.554168 -0.481184 -0.363260   
3       no   unknown -1.265746   may       579 -0.554168 -0.481184 -0.363260   
4       no   unknown -1.265746   may       673 -0.186785 -0.481184 -0.363260   
...    ...       ...       ...   ...       ...       ...       ...       ...   
11157   no  cellular  0.515650   apr       257 -0.554168 -0.481184 -0.363260   
11158   no   unknown  0.040612   jun        83  0.547981 -0.481184 -0.363260   
11159   no  cellular  0.396891   aug       156 -0.186785 -0.481184 -0.363260   
11160  yes  cellular -0.909466   may         9 -0.186785  1.109571  1.818332   
11161   no  cellular -0.790707   jul       628 -0.554168 -0.481184 -0.363260   

      poutcome deposit  
0      unknown     yes  
1      unknown     yes  
2      unknown     yes  
3      unknown     yes  
4      unknown     yes  
...        ...     ...  
11157  unknown      no  
11158  unknown      no  
11159  unknown      no  
11160  failure      no  
11161  unknown      no  

[11162 rows x 17 columns]

#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [ ]:
data = pd.read_csv('Lab/Lab6/bank.csv',encoding='utf-8')

In [ ]:
enc = OneHotEncoder(handle_unknown='ignore')
dt1 = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome','deposit']
dataset = data[dt1]
data = pd.get_dummies(data,columns=['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome','deposit'])
data

age  balance  day  duration  campaign  pdays  previous  job_admin.  \
0       59     2343    5      1042         1     -1         0           1   
1       56       45    5      1467         1     -1         0           1   
2       41     1270    5      1389         1     -1         0           0   
3       55     2476    5       579         1     -1         0           0   
4       54      184    5       673         2     -1         0           1   
...    ...      ...  ...       ...       ...    ...       ...         ...   
11157   33        1   20       257         1     -1         0           0   
11158   39      733   16        83         4     -1         0           0   
11159   32       29   19       156         2     -1         0           0   
11160   43        0    8         9         2    172         5           0   
11161   34        0    9       628         1     -1         0           0   

       job_blue-collar  job_entrepreneur  ...  month_may  month_nov  \
0                    0                 0  ...          1          0   
1                    0                 0  ...          1          0   
2                    0                 0  ...          1          0   
3                    0                 0  ...          1          0   
4                    0                 0  ...          1          0   
...                ...               ...  ...        ...        ...   
11157                1                 0  ...          0          0   
11158                0                 0  ...          0          0   
11159                0                 0  ...          0          0   
11160                0                 0  ...          1          0   
11161                0                 0  ...          0          0   

       month_oct  month_sep  poutcome_failure  poutcome_other  \
0              0          0                 0               0   
1              0          0                 0               0   
2              0          0                 0               0   
3              0          0                 0               0   
4              0          0                 0               0   
...          ...        ...               ...             ...   
11157          0          0                 0               0   
11158          0          0                 0               0   
11159          0          0                 0               0   
11160          0          0                 1               0   
11161          0          0                 0               0   

       poutcome_success  poutcome_unknown  deposit_no  deposit_yes  
0                     0                 1           0            1  
1                     0                 1           0            1  
2                     0                 1           0            1  
3                     0                 1           0            1  
4                     0                 1           0            1  
...                 ...               ...         ...          ...  
11157                 0                 1           1            0  
11158                 0                 1           1            0  
11159                 0                 1           1            0  
11160                 0                 0           1            0  
11161                 0                 1           1            0  

[11162 rows x 53 columns]

#3.3. Apply **Decision tree, Random forest, kNN, NaïveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [ ]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Decision tree
det = tree.DecisionTreeClassifier()

In [ ]:
det.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = det.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred)

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[1166    0]
 [   0 1067]]


In [ ]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre = round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [ ]:
# Random
rand =RandomForestClassifier(n_estimators=100)

In [ ]:
rand.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred1 = rand.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred1)

In [ ]:
print(confusion_matrix(y_test, y_pred1))

[[1166    0]
 [   0 1067]]


In [ ]:
acc1 = round(accuracy_score(y_test, y_pred1), 2)
pre1 = round(precision_score(y_test, y_pred1, average='micro'), 2)
recall1 = round(recall_score(y_test, y_pred1, average='micro'), 2)
f11 = round(f1_score(y_test, y_pred1, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred1))
print ("Precision : ", precision_score(y_test, y_pred1,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred1, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred1, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [ ]:
#KNN
model = KNeighborsClassifier(n_neighbors=3)

In [ ]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred2 = model.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred2)

In [ ]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_pred2))

Confusion matrix :
 [[889 277]
 [307 760]]


In [ ]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2 = round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12= round(f1_score(y_test, y_pred2, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  0.7384684281236006
Precision :  0.7384684281236006
Recall :  0.7384684281236006
F1 :  0.7384684281236006


In [ ]:
# NaïveBayes
gau = GaussianNB()

In [ ]:
gau.fit(X_train, y_train) 

GaussianNB()

In [ ]:
y_pred3 = gau.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_pred3)

In [ ]:

print ("Confusion matrix :\n", confusion_matrix(y_test, y_pred3))

Confusion matrix :
 [[1164    2]
 [   0 1067]]


In [ ]:
acc3 = round(accuracy_score(y_test, y_pred3), 2)
pre3 = round(precision_score(y_test, y_pred3, average='micro'), 2)
recall3 = round(recall_score(y_test, y_pred3, average='micro'), 2)
f13 = round(f1_score(y_test, y_pred3, average='micro'), 2)


In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_pred3))
print ("Precision : ", precision_score(y_test, y_pred3,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred3, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred3, average='micro'))

Accuracy :  0.9991043439319302
Precision :  0.9991043439319302
Recall :  0.9991043439319302
F1 :  0.9991043439319302


In [ ]:
from prettytable import PrettyTable

t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])

t.add_row(['Decision Tree',acc,pre,recall,f1])
t.add_row(['Random forest',acc1,pre1,recall1,f11])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['NaiveBayes',acc3,pre3,recall3,f13])
print(t)

+---------------+----------+-----------+--------+------+
|    Compare    | Accuracy | Precision | Recall |  F1  |
+---------------+----------+-----------+--------+------+
| Decision Tree |   1.0    |    1.0    |  1.0   | 1.0  |
| Random forest |   1.0    |    1.0    |  1.0   | 1.0  |
|      kNN      |   0.74   |    0.74   |  0.74  | 0.74 |
|   NaiveBayes  |   1.0    |    1.0    |  1.0   | 1.0  |
+---------------+----------+-----------+--------+------+


#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3. 

In [ ]:
array = data.values
X = array[:, :-1]
Y = array[:, -1]

In [ ]:
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, Y)
print(model.feature_importances_)

[3.72429613e-03 3.22988111e-03 3.67461450e-03 3.36028708e-02
 3.05972157e-03 2.88272470e-03 1.01454435e-03 6.04874720e-04
 7.64155376e-04 4.73105432e-04 2.79464427e-04 6.99461403e-04
 9.11437953e-04 6.03285321e-04 7.15897912e-04 4.15746280e-04
 7.45170835e-04 4.57539638e-04 2.75777561e-04 7.17748157e-04
 2.34434909e-03 1.54746804e-03 7.40972603e-04 1.19596115e-03
 1.77629857e-03 4.49604730e-04 2.00446843e-04 2.60417422e-04
 2.54021281e-03 1.06813242e-02 1.49736914e-03 2.54381056e-03
 1.43778168e-02 8.93492492e-04 1.26276521e-02 2.75953792e-03
 3.98556373e-03 2.27617351e-04 5.47593597e-04 6.17194968e-04
 7.71558482e-04 2.22896506e-03 4.14773149e-03 2.57800364e-03
 7.19095584e-04 4.68544844e-03 3.83353202e-03 3.27197158e-03
 4.85987459e-04 3.62326989e-02 1.28297356e-02 8.07548249e-01]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [ ]:
# Decision Tree
clf = tree.DecisionTreeClassifier()

In [ ]:
clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_preda = clf.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_preda)

In [ ]:
print(confusion_matrix(y_test, y_preda))

[[1742    0]
 [   0 1607]]


In [ ]:
acca = round(accuracy_score(y_test, y_preda), 2)
prea = round(precision_score(y_test, y_preda, average='micro'), 2)
recalla = round(recall_score(y_test, y_preda, average='micro'), 2)
f1a = round(f1_score(y_test, y_preda, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_preda))
print ("Precision : ", precision_score(y_test, y_preda,average='micro'))
print ("Recall : ", recall_score(y_test, y_preda, average='micro'))
print ("F1 : ", f1_score(y_test, y_preda, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [ ]:
# Random
clf1=RandomForestClassifier(n_estimators=100)
clf1.fit(X,Y)

RandomForestClassifier()

In [ ]:
y_predb = clf1.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_predb)

In [ ]:
print(confusion_matrix(y_test, y_predb))

[[1742    0]
 [   0 1607]]


In [ ]:
accb = round(accuracy_score(y_test, y_predb), 2)
preb = round(precision_score(y_test, y_predb, average='micro'), 2)
recallb = round(recall_score(y_test, y_predb, average='micro'), 2)
f1b = round(f1_score(y_test, y_predb, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_predb))
print ("Precision : ", precision_score(y_test, y_predb,average='micro'))
print ("Recall : ", recall_score(y_test, y_predb, average='micro'))
print ("F1 : ", f1_score(y_test, y_predb, average='micro'))

Accuracy :  1.0
Precision :  1.0
Recall :  1.0
F1 :  1.0


In [ ]:
#KNN
model = KNeighborsClassifier(n_neighbors=3)

In [ ]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_predc = model.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_predc)

In [ ]:
print(confusion_matrix(y_test, y_predc))

[[1324  418]
 [ 464 1143]]


In [ ]:
accc = round(accuracy_score(y_test, y_predc), 2)
prec = round(precision_score(y_test, y_predc, average='micro'), 2)
recallc = round(recall_score(y_test, y_predc, average='micro'), 2)
f1c = round(f1_score(y_test, y_predc, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_predc))
print ("Precision : ", precision_score(y_test, y_predc,average='micro'))
print ("Recall : ", recall_score(y_test, y_predc, average='micro'))
print ("F1 : ", f1_score(y_test, y_predc, average='micro'))

Accuracy :  0.7366378023290534
Precision :  0.7366378023290534
Recall :  0.7366378023290534
F1 :  0.7366378023290534


In [ ]:
# NaïveBayes
gau = GaussianNB()

GaussianNB()

In [ ]:
y_predd = gau.predict(X_test)

In [ ]:
confusion = confusion_matrix(y_test, y_predd)

In [ ]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_predd))

Confusion matrix :
 [[1740    2]
 [   0 1607]]


In [ ]:
accd = round(accuracy_score(y_test, y_predd), 2)
pred = round(precision_score(y_test, y_predd, average='micro'), 2)
recalld = round(recall_score(y_test, y_predd, average='micro'), 2)
f1d = round(f1_score(y_test, y_predd, average='micro'), 2)

In [ ]:
print ("Accuracy : ", accuracy_score(y_test, y_predd))
print ("Precision : ", precision_score(y_test, y_predd,average='micro'))
print ("Recall : ", recall_score(y_test, y_predd, average='micro'))
print ("F1 : ", f1_score(y_test, y_predd, average='micro'))

Accuracy :  0.9994028068080024
Precision :  0.9994028068080024
Recall :  0.9994028068080024
F1 :  0.9994028068080024


In [ ]:
from prettytable import PrettyTable

t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])

t.add_row(['Decision Tree',acc,pre,recall,f1])
t.add_row(['Decision Tree',acca,prea,recalla,f1a])
t.add_row(['Random forest',acc1,pre1,recall1,f11])
t.add_row(['Random forest',accb,preb,recallb,f1b])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['kNN',accc,prec,recallc,f1c])
t.add_row(['NaiveBayes',acc3,pre3,recall3,f13])
t.add_row(['NaiveBayes',accd,pred,recalld,f1d])
print(t)

+---------------+----------+-----------+--------+------+
|    Compare    | Accuracy | Precision | Recall |  F1  |
+---------------+----------+-----------+--------+------+
| Decision Tree |   1.0    |    1.0    |  1.0   | 1.0  |
| Decision Tree |   1.0    |    1.0    |  1.0   | 1.0  |
| Random forest |   1.0    |    1.0    |  1.0   | 1.0  |
| Random forest |   1.0    |    1.0    |  1.0   | 1.0  |
|      kNN      |   0.74   |    0.74   |  0.74  | 0.74 |
|      kNN      |   0.74   |    0.74   |  0.74  | 0.74 |
|   NaiveBayes  |   1.0    |    1.0    |  1.0   | 1.0  |
|   NaiveBayes  |   1.0    |    1.0    |  1.0   | 1.0  |
+---------------+----------+-----------+--------+------+


#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.


In [6]:
# code
data = pd.read_csv('Lab/Lab5/creditcard.csv')
data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [56]:
X= data.iloc[:,0:30]
Y= data.iloc[:,30]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, train_size=0.7,  random_state = 1)

In [57]:
# Decision Tree
dt1 = tree.DecisionTreeClassifier()

In [58]:
dt1.fit(X_train, y_train)

DecisionTreeClassifier()

In [59]:
y_pred = dt1.predict(X_test)

In [60]:
confusion = confusion_matrix(y_test, y_pred)

In [61]:
print(confusion_matrix(y_test, y_pred))

[[85271    37]
 [   36    99]]


In [62]:
acc = round(accuracy_score(y_test, y_pred), 2)
pre = round(precision_score(y_test, y_pred, average='micro'), 2)
recall = round(recall_score(y_test, y_pred, average='micro'), 2)
f1 = round(f1_score(y_test, y_pred, average='micro'), 2)

In [63]:
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print ("Precision : ", precision_score(y_test, y_pred,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred, average='micro'))

Accuracy :  0.9991456292499094
Precision :  0.9991456292499094
Recall :  0.9991456292499094
F1 :  0.9991456292499094


In [64]:
# Random
ran =RandomForestClassifier(n_estimators=100)

In [65]:
ran.fit(X_train,y_train)

RandomForestClassifier()

In [66]:
y_pred1 = ran.predict(X_test)

In [67]:
confusion = confusion_matrix(y_test, y_pred1)

In [68]:
print(confusion_matrix(y_test, y_pred1))

[[85297    11]
 [   31   104]]


In [69]:
acc1 = round(accuracy_score(y_test, y_pred1), 2)
pre1 = round(precision_score(y_test, y_pred1, average='micro'), 2)
recall1 = round(recall_score(y_test, y_pred1, average='micro'), 2)
f11 = round(f1_score(y_test, y_pred1, average='micro'), 2)

In [70]:
print ("Accuracy : ", accuracy_score(y_test, y_pred1))
print ("Precision : ", precision_score(y_test, y_pred1,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred1, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred1, average='micro'))

Accuracy :  0.9995084442259752
Precision :  0.9995084442259752
Recall :  0.9995084442259752
F1 :  0.9995084442259752


In [71]:
#KNN
model1 = KNeighborsClassifier(n_neighbors=3)

In [72]:
model1.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [73]:
y_pred2 = model1.predict(X_test)

In [74]:
confusion = confusion_matrix(y_test, y_pred2)

In [75]:
print(confusion_matrix(y_test, y_pred2))

[[85307     1]
 [  130     5]]


In [76]:
acc2 = round(accuracy_score(y_test, y_pred2), 2)
pre2 = round(precision_score(y_test, y_pred2, average='micro'), 2)
recall2 = round(recall_score(y_test, y_pred2, average='micro'), 2)
f12 = round(f1_score(y_test, y_pred2, average='micro'), 2)

In [77]:
print ("Accuracy : ", accuracy_score(y_test, y_pred2))
print ("Precision : ", precision_score(y_test, y_pred2,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred2, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred2, average='micro'))

Accuracy :  0.9984668141333989
Precision :  0.9984668141333989
Recall :  0.9984668141333989
F1 :  0.9984668141333989


In [78]:
# NaïveBayes
gau1 = GaussianNB()

In [79]:
gau1.fit(X_train, y_train)

GaussianNB()

In [80]:
y_pred3 = gau1.predict(X_test)

In [81]:
confusion = confusion_matrix(y_test, y_pred3)

In [82]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_pred3))

Confusion matrix :
 [[84787   521]
 [   49    86]]


In [83]:
acc3 = round(accuracy_score(y_test, y_pred3), 2)
pre3 = round(precision_score(y_test, y_pred3, average='micro'), 2)
recall3 = round(recall_score(y_test, y_pred3, average='micro'), 2)
f13 = round(f1_score(y_test, y_pred3, average='micro'), 2)

In [84]:
print ("Accuracy : ", accuracy_score(y_test, y_pred3))
print ("Precision : ", precision_score(y_test, y_pred3,average='micro'))
print ("Recall : ", recall_score(y_test, y_pred3, average='micro'))
print ("F1 : ", f1_score(y_test, y_pred3, average='micro'))

Accuracy :  0.9933288859239493
Precision :  0.9933288859239493
Recall :  0.9933288859239493
F1 :  0.9933288859239493


In [21]:
data = pd.read_csv('Lab/Lab5/creditcard.csv')
array = data.values
X = array[:,0:30]
Y = array[:,30]

In [8]:
# feature extraction
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:10,:])

[4.325e+01 2.956e+03 2.393e+03 1.101e+04 5.164e+03 2.592e+03 5.435e+02
 1.035e+04 1.125e+02 2.747e+03 1.406e+04 6.999e+03 2.075e+04 5.948e+00
 2.870e+04 5.080e+00 1.144e+04 3.398e+04 3.584e+03 3.450e+02 1.150e+02
 4.659e+02 1.847e-01 2.053e+00 1.485e+01 3.116e+00 5.654e+00 8.805e+01
 2.590e+01 9.033e+00]
[[ 0.091 -0.618 -0.311  0.208]
 [-0.167  1.065 -0.144 -0.115]
 [ 0.208  0.066 -0.166  1.11 ]
 [-0.055  0.178 -0.288 -0.684]
 [ 0.753  0.538 -1.12  -0.237]
 [-0.371  0.36  -0.137 -0.058]
 [-0.099 -0.154  0.167  0.003]
 [ 1.249  0.291 -1.324 -1.222]
 [-0.41  -0.11   0.074 -0.5  ]
 [-0.367  0.836 -0.444 -0.541]]


In [117]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state = 42)

In [118]:
ran2=RandomForestClassifier(n_estimators=100)
ran2.fit(X_train,y_train)

RandomForestClassifier()

In [119]:
y_predb = ran2.predict(X_test)

In [120]:
confusion = confusion_matrix(y_test, y_predb)

In [121]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_predb))

Confusion matrix :
 [[56862     2]
 [   21    77]]


In [122]:
accb = round(accuracy_score(y_test, y_predb), 2)
preb = round(precision_score(y_test, y_predb, average='micro'), 2)
recallb = round(recall_score(y_test, y_predb, average='micro'), 2)
f1b = round(f1_score(y_test, y_predb, average='micro'), 2)


In [123]:
print ("Accuracy : ", accuracy_score(y_test, y_predb))
print ("Precision : ", precision_score(y_test, y_predb,average='micro'))
print ("Recall : ", recall_score(y_test, y_predb, average='micro'))
print ("F1 : ", f1_score(y_test, y_predb, average='micro'))

Accuracy :  0.9995962220427653
Precision :  0.9995962220427653
Recall :  0.9995962220427653
F1 :  0.9995962220427653


In [124]:
# Decision Tree
dt2 = tree.DecisionTreeClassifier()

In [125]:
dt2.fit(X_train, y_train)

DecisionTreeClassifier()

In [126]:
y_preda = dt2.predict(X_test)

In [127]:
confusion = confusion_matrix(y_test, y_preda)

In [128]:
print(confusion_matrix(y_test, y_preda))

[[56835    29]
 [   21    77]]


In [129]:
acca = round(accuracy_score(y_test, y_preda), 2)
prea = round(precision_score(y_test, y_preda, average='micro'), 2)
recalla = round(recall_score(y_test, y_preda, average='micro'), 2)
f1a = round(f1_score(y_test, y_preda, average='micro'), 2)

In [130]:
print ("Accuracy : ", accuracy_score(y_test, y_preda))
print ("Precision : ", precision_score(y_test, y_preda,average='micro'))
print ("Recall : ", recall_score(y_test, y_preda, average='micro'))
print ("F1 : ", f1_score(y_test, y_preda, average='micro'))

Accuracy :  0.9991222218320986
Precision :  0.9991222218320986
Recall :  0.9991222218320986
F1 :  0.9991222218320986


In [131]:
#KNN
model2 = KNeighborsClassifier(n_neighbors=3)


In [132]:
model2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [133]:
y_predc = model2.predict(X_test)

In [134]:
confusion = confusion_matrix(y_test, y_predc)

In [135]:
print(confusion_matrix(y_test, y_predc))

[[56864     0]
 [   89     9]]


In [136]:
accc = round(accuracy_score(y_test, y_predc), 2)
prec = round(precision_score(y_test, y_predc, average='micro'), 2)
recallc = round(recall_score(y_test, y_predc, average='micro'), 2)
f1c = round(f1_score(y_test, y_predc, average='micro'), 2)

In [137]:
print ("Accuracy : ", accuracy_score(y_test, y_predc))
print ("Precision : ", precision_score(y_test, y_predc,average='micro'))
print ("Recall : ", recall_score(y_test, y_predc, average='micro'))
print ("F1 : ", f1_score(y_test, y_predc, average='micro'))

Accuracy :  0.9984375548611355
Precision :  0.9984375548611355
Recall :  0.9984375548611355
F1 :  0.9984375548611355


In [138]:
# NaïveBayes
gau2 = GaussianNB()

In [139]:
gau2.fit(X_train, y_train)

GaussianNB()

In [140]:
y_predd = gau2.predict(X_test)

In [141]:
confusion = confusion_matrix(y_test, y_predd)

In [142]:
print ("Confusion matrix :\n", confusion_matrix(y_test, y_predd))

Confusion matrix :
 [[56502   362]
 [   36    62]]


In [143]:
accd = round(accuracy_score(y_test, y_predd), 2)
pred = round(precision_score(y_test, y_predd, average='micro'), 2)
recalld = round(recall_score(y_test, y_predd, average='micro'), 2)
f1d = round(f1_score(y_test, y_predd, average='micro'), 2)

In [144]:
print ("Accuracy : ", accuracy_score(y_test, y_predd))
print ("Precision : ", precision_score(y_test, y_predd,average='micro'))
print ("Recall : ", recall_score(y_test, y_predd, average='micro'))
print ("F1 : ", f1_score(y_test, y_predd, average='micro'))

Accuracy :  0.9930128857835048
Precision :  0.9930128857835048
Recall :  0.9930128857835048
F1 :  0.9930128857835048


In [145]:
from prettytable import PrettyTable

t = PrettyTable(['Compare','Accuracy','Precision','Recall','F1'])

t.add_row(['Decision Tree',acc,pre,recall,f1])
t.add_row(['Decision Tree',acca,prea,recalla,f1a])
t.add_row(['Random forest',acc1,pre1,recall1,f11])
t.add_row(['Random forest',accb,preb,recallb,f1b])
t.add_row(['kNN',acc2,pre2,recall2,f12])
t.add_row(['kNN',accc,prec,recallc,f1c])
t.add_row(['NaiveBayes',acc3,pre3,recall3,f13])
t.add_row(['NaiveBayes',accd,pred,recalld,f1d])
print(t)

+---------------+----------+-----------+--------+------+
|    Compare    | Accuracy | Precision | Recall |  F1  |
+---------------+----------+-----------+--------+------+
| Decision Tree |   1.0    |    1.0    |  1.0   | 1.0  |
| Decision Tree |   1.0    |    1.0    |  1.0   | 1.0  |
| Random forest |   1.0    |    1.0    |  1.0   | 1.0  |
| Random forest |   1.0    |    1.0    |  1.0   | 1.0  |
|      kNN      |   1.0    |    1.0    |  1.0   | 1.0  |
|      kNN      |   1.0    |    1.0    |  1.0   | 1.0  |
|   NaiveBayes  |   0.99   |    0.99   |  0.99  | 0.99 |
|   NaiveBayes  |   0.99   |    0.99   |  0.99  | 0.99 |
+---------------+----------+-----------+--------+------+


#Finally,
Save a copy in your Github. Remember renaming the notebook.